version: '3.6'

services:
  docker:
    image: docker:18.03.1-ce-dind
    privileged: true
    command: ["--storage-driver=overlay2"]
    volumes:
      - docker_lib:/var/lib/docker
      - cache:/cache
      - builds:/builds
    networks:
      gitlab-runner-net:
        aliases:
          - host.docker.gitlab

  runner:
    image: gitlab/gitlab-runner:${RUNNER_IMAGE_TAG}
    volumes:
      - ./config:/etc/gitlab-runner
    networks:
      - gitlab-runner-net

networks:
  gitlab-runner-net:


volumes:
  docker_lib:
  cache:
  builds:
